/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'HealthCheckAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; version: string; timestamp: string; services: { database: string; queue: string; ai: string } }>, never>
    'UploadResumeAPI': ApiRouteHandler<{ fileName: string; fileType: 'pdf' | 'docx'; fileContent: string; fileSize: number }, ApiResponse<200, { message: string; resumeId: string; status: string }> | ApiResponse<400, { error: string }>, never>
    'UpdateProfileAPI': ApiRouteHandler<{ skills?: Array<string>; experienceYears?: number; preferredRoles?: Array<string>; preferredLocations?: Array<string>; remoteOnly?: boolean; salaryRange?: { min: number; max: number } }, ApiResponse<200, { message: string; profile: { userId: string; skills: Array<string>; experienceYears: number; preferredRoles: Array<string> } }> | ApiResponse<401, { error: string }>, never>
    'GetProfileAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { profile: { userId: string; name?: string; email?: string; skills: Array<string>; experienceYears: number; preferredRoles: Array<string>; education: Array<string>; resumeId?: string } }> | ApiResponse<401, { error: string }>, never>
    'SearchJobsAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { jobs: Array<{ id: string; title: string; company: string; location: string; remote: boolean; salary?: string; description: string; applyUrl: string; postedAt: string; matchScore?: number }>; total: number; page: number; totalPages: number }> | ApiResponse<401, { error: string }>, never>
    'GetJobMatchesAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { matches: Array<{ jobId: string; jobTitle: string; company: string; overallScore: number; matchingSkills: Array<string>; missingSkills: Array<string>; recommendation: string }>; profileStrength: number; suggestions: Array<string> }> | ApiResponse<401, { error: string }>, never>
    'GetJobDetailsAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { job: { id: string; title: string; company: string; location: string; remote: boolean; salary?: string; description: string; requirements: Array<string>; benefits: Array<string>; applyUrl: string; postedAt: string }; matchAnalysis: { score: number; matchingSkills: Array<string>; missingSkills: Array<string>; recommendation: string } }> | ApiResponse<404, { error: string }>, never>
    'GetDashboardAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { user: { name: string; email: string; profileComplete: boolean }; applications: { total: number; applied: number; interview: number; offer: number; rejected: number; recentApplications: Array<{ id: string; jobTitle: string; company: string; status: string; appliedAt?: string }> }; socialMedia: { connectedPlatforms: Array<string>; scheduledPosts: number; publishedThisWeek: number }; jobMatches: { newMatches: number; topMatch?: { jobTitle: string; company: string; score: number } } }> | ApiResponse<401, { error: string }>, never>
    'RegisterAPI': ApiRouteHandler<{ email: string; password: string; name: string }, ApiResponse<201, { message: string; token: string; user: { id: string; email: string; name: string } }> | ApiResponse<400, { error: string }>, never>
    'OAuthCallbackAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; provider: string; connected: boolean }> | ApiResponse<400, { error: string }>, never>
    'LoginAPI': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { message: string; token: string; user: { id: string; email: string; name: string } }> | ApiResponse<401, { error: string }>, never>
    'UpdateApplicationStatusAPI': ApiRouteHandler<{ status: 'draft' | 'applied' | 'interview' | 'offer' | 'rejected' | 'withdrawn'; notes?: string; interviewDate?: string }, ApiResponse<200, { message: string; application: { id: string; status: string; updatedAt: string } }> | ApiResponse<404, { error: string }>, never>
    'GetApplicationsAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { applications: Array<{ id: string; jobId: string; jobTitle: string; company: string; status: string; appliedAt?: string; interviewDate?: string; notes?: string; createdAt: string }>; stats: { total: number; applied: number; interview: number; offer: number; rejected: number } }> | ApiResponse<401, { error: string }>, never>
    'AssistedApplyAPI': ApiRouteHandler<{ generateCoverLetter: boolean; customMessage?: string }, ApiResponse<200, { applicationId: string; status: string; applyUrl: string; coverLetter?: string; prefillData?: { name: string; email: string; phone?: string; skills: Array<string>; experience: string } }> | ApiResponse<400, { error: string }>, never>
  }
    
}